routes/web.php
<?php

Auth::routes();

Route::get('/', 'VacancyController@index');

Route::resource('vacancy', 'VacancyController')->except([
    'show'
]);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that contain dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at', 'updated_at'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Vacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Vacancy extends Model
{
    use SoftDeletes;

    /**
     * The name of the table.
     *
     * @var string $table
     */
    protected $table = 'vacancies';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'content'
    ];

    /**
     * The attributes that contain dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at', 'updated_at', 'deleted_at'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/VacancyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\VacancyStoreRequest;
use App\Http\Requests\VacancyUpdateRequest;
use App\Services\VacancyFilterService;
use App\Services\VacancyService;
use App\Vacancy;

class VacancyController extends Controller
{
    /**
     * @var VacancyFilterService
     */
    private $vacancyFilterService;
    /**
     * @var VacancyService
     */
    private $vacancyService;

    /**
     * VacancyController constructor.
     * @param VacancyFilterService $vacancyFilterService
     * @param VacancyService $vacancyService
     */
    public function __construct(VacancyFilterService $vacancyFilterService, VacancyService $vacancyService)
    {
        $this->middleware('is_admin')->only(['edit', 'update', 'destroy']);

        $this->vacancyFilterService = $vacancyFilterService;
        $this->vacancyService = $vacancyService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vacancies = Vacancy::get();

        return view('pages.index', compact('vacancies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param VacancyStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(VacancyStoreRequest $request)
    {
        $vacancy = $this->vacancyService->store($request);

        if (!$vacancy) {
            return back()->withInput($request->all());
        }

        return redirect(route('vacancy.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Vacancy $vacancy
     * @return \Illuminate\Http\Response
     */
    public function edit(Vacancy $vacancy)
    {
        return view('pages.edit', compact('vacancy'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param VacancyUpdateRequest $request
     * @param Vacancy $vacancy
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(VacancyUpdateRequest $request, Vacancy $vacancy)
    {
        $this->vacancyService->update($request, $vacancy);

        return redirect(route('vacancy.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Vacancy $vacancy
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function destroy(Vacancy $vacancy)
    {
        $vacancy->delete();

        return redirect(route('vacancy.index'));
    }
}

resources/views/home.blade.php
{{--@extends('layouts.app')--}}

{{--@section('content')--}}
{{--<div class="container">--}}
    {{--<div class="row justify-content-center">--}}
        {{--<div class="col-md-8">--}}
            {{--<div class="card">--}}
                {{--<div class="card-header">Dashboard</div>--}}

                {{--<div class="card-body">--}}
                    {{--@if (session('status'))--}}
                        {{--<div class="alert alert-success" role="alert">--}}
                            {{--{{ session('status') }}--}}
                        {{--</div>--}}
                    {{--@endif--}}

                    {{--You are logged in!--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}
{{--</div>--}}
{{--@endsection--}}

@extends('layouts.master')

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
@include('components.header')


<body class="fixed-navbar sidebar-scroll">

@include('components.top-nav')

<!-- Navigation -->
@include('components.nav')

<!-- Main Wrapper -->
<div id="wrapper">

    @yield('content')

    <!-- Right sidebar -->
    @include('components.newsletter')
    <!-- Footer-->
    <footer class="footer">
        <span class="pull-right">
           Powered by: Homer template
        </span>
        Jessey van Offeren
    </footer>

</div>

<!-- Vendor scripts -->
<script src="/homer/vendor/jquery-flot/jquery.flot.js"></script>
<script src="/homer/vendor/jquery-flot/jquery.flot.resize.js"></script>
<script src="/homer/vendor/jquery-flot/jquery.flot.pie.js"></script>
<script src="/homer/vendor/flot.curvedlines/curvedLines.js"></script>
<script src="/homer/vendor/jquery.flot.spline/index.js"></script>
<script src="/homer/vendor/metisMenu/dist/metisMenu.min.js"></script>
<script src="/homer/vendor/iCheck/icheck.min.js"></script>
<script src="/homer/vendor/peity/jquery.peity.min.js"></script>
<script src="/homer/vendor/sparkline/index.js"></script>

<!-- App scripts -->
<script src="/homer/scripts/homer.js"></script>

</body>
</html>

resources/views/pages/create.blade.php
@extends('layouts.master')

@section('content')
    <link rel="stylesheet" href="/homer/vendor/summernote/dist/summernote.css" />
    <link rel="stylesheet" href="/homer/vendor/summernote/dist/summernote-bs3.css" />
    <link rel="stylesheet" href="/homer/vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css" />
    <link rel="stylesheet" href="/homer/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />


    <div class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="hpanel">
                    <div class="panel-heading">
                        Create Article
                    </div>
                    <div class="panel-body">

                        @foreach ($errors->all() as $message)
                            <div class="alert-danger">{{ $message }}</div>
                        @endforeach

                        <form method="post" action="{{ route('vacancy.store') }}" class="form-horizontal">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Title</label>
                                <div class="col-sm-10">
                                    <input type="text" name="title" id="article_title" value="{{ old('title') }}" class="form-control" required>
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Content</label>
                                <div class="col-sm-10">
                                    <textarea class="input-block-level summernote" name="content" rows="18" required>{{ old('content') }}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-8 col-sm-offset-2">
                                    <button class="btn btn-primary" type="submit">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="/homer/vendor/summernote/dist/summernote.min.js"></script>

    <script>

        $(function () {
            $('.summernote').summernote({ height: 300});
        });
    </script>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.master')

@section('content')
    <link rel="stylesheet" href="/homer/vendor/summernote/dist/summernote.css" />
    <link rel="stylesheet" href="/homer/vendor/summernote/dist/summernote-bs3.css" />
    <link rel="stylesheet" href="/homer/vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css" />
    <link rel="stylesheet" href="/homer/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />


    <div class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="hpanel">
                    <div class="panel-heading">
                        Update Vacancy
                    </div>
                    <div class="panel-body">

                        @foreach ($errors->all() as $message)
                            <div class="alert-danger">{{ $message }}</div>
                        @endforeach

                        <form method="post" action="{{ route('vacancy.update', ['id' => $vacancy->id]) }}" class="form-horizontal">

                            {{ method_field('put') }}
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Title</label>
                                <div class="col-sm-10">
                                    <input type="text" name="title" id="article_title" value="{{ old('title', $vacancy->title) }}" class="form-control" required>
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Content</label>
                                <div class="col-sm-10">
                                    <textarea class="input-block-level summernote" name="content" rows="18" required>{!! old('content', $vacancy->content) !!}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-8 col-sm-offset-2">
                                    <button class="btn btn-primary" type="submit">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="/homer/vendor/summernote/dist/summernote.min.js"></script>

    <script>

        $(function () {
            $('.summernote').summernote({ height: 300});
        });
    </script>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.master')

@section('content')

    <script src="/homer/vendor/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="/homer/vendor/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <div class="normalheader ">
        <div class="hpanel">
            <div class="panel-body">

                <div id="hbreadcrumb" class="pull-right m-t-lg">
                    <ol class="hbreadcrumb breadcrumb">
                        <li>
                            <a href="{{ route('vacancy.create') }}">
                                <button class="btn btn-info"><i class="fa fa-plus"></i> Create</button>
                            </a>
                        </li>
                    </ol>
                </div>
                <h2 class="font-light m-b-xs">
                    Vacancies
                </h2>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="hpanel">
                    <div class="panel-body">
                        <table id="article_table" class="table table-striped table-bordered table-hover" width="100%">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Created At</th>
                                @auth
                                    @if(Auth::user()->is_admin === 1)
                                        <th>actions</th>
                                    @endif
                                @endauth
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($vacancies as $vacancy)
                                <tr>
                                    <td>{{ $vacancy->title }}</td>
                                    <td>{{ $vacancy->created_at }}</td>
                                    @auth
                                        @if(Auth::user()->is_admin === 1)
                                            <td>
                                                <a href="{{ route('vacancy.edit', ['id' => $vacancy->id]) }}"><span><i class="fa fa-edit"></i></span></a>
                                                -
                                                <a onclick="event.preventDefault();
                                                    document.getElementById('vacancy-{{ $vacancy->id }}').submit();">
                                                    <span><i class="fa fa-trash"></i></span>
                                                </a>
                                                <form id="vacancy-{{ $vacancy->id }}" action="{{ route('vacancy.destroy', ['id' => $vacancy->id]) }}" method="POST" style="display: none;">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                </form>
                                            </td>
                                        @endif
                                    @endauth
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Initialize Example 2
        $('#article_table').dataTable();

    </script>
@endsection